[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend server"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn[standard]"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
